version: "3.9"

services:
  database:
    image: postgres:14.5-alpine
    environment:
      POSTGRES_DB: reservation
      POSTGRES_USER: username
      POSTGRES_PASSWORD: 1234
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"